# src/config.py
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA_ROOT = os.path.join(ROOT, "data", "GRAZPEDWri-DX")

# Images: we treat part1/2/3 as train, part4 as test (no manual copying needed).
IMAGE_PARTS_TRAIN = [os.path.join(DATA_ROOT, p) for p in ("images_part1", "images_part2", "images_part3")]
IMAGE_PART_TEST = os.path.join(DATA_ROOT, "images_part4")

ORIG_CSV = os.path.join(DATA_ROOT, "dataset.csv")
EVAL_CSV = os.path.join(DATA_ROOT, "eval_image_paths.csv")      # created by build_graz_csv.py
TRAIN_CSV = os.path.join(DATA_ROOT, "graz_train.csv")          # generated by build_graz_csv.py
TEST_CSV = os.path.join(DATA_ROOT, "graz_test.csv")            # generated by build_graz_csv.py

SRC_DIR = os.path.abspath(os.path.dirname(__file__))
MODELS_DIR = os.path.join(SRC_DIR, "models")
os.makedirs(MODELS_DIR, exist_ok=True)

RESULTS_DIR = os.path.join(ROOT, "outputs")
os.makedirs(RESULTS_DIR, exist_ok=True)

# training hyperparams
IMG_SIZE = 256
BATCH_SIZE = 8
LR = 1e-4
EPOCHS = 20
BACKBONE = "swinv2_base_window8_256"
NUM_WORKERS = 4
DEVICE = "cuda" if os.environ.get("CUDA_VISIBLE_DEVICES", None) else ("cuda" if __import__("torch").cuda.is_available() else "cpu")
